language: node_js
node_js:
  - '4'
  - '5'
  - '6'

# fail asap when there is a failure
matrix:
  fast_finish: true

# cache node modules
cache:
  directories:
    - node_modules

before_install:
  # faster npm install
  - npm set progress false
  # remove useless/non listed deps
  - npm prune

after_success: npm run coverage
